config/routes.rb
Rails.application.routes.draw do
  root 'battleship_games#index'

  resources :battleship_games, :battleships

end

app/models/battleship.rb
class Battleship < ActiveRecord::Base
  belongs_to :battleship_game

  def is_at(i, j)
    if self.orientation == "horizontal"
      return i == self.row && (0...self.length).cover?(j - self.column)
    else
      return j == self.column && (0...self.length).cover?(i - self.row)
    end
  end

end

app/models/battleship_game.rb
class BattleshipGame < ActiveRecord::Base
  has_many :battleships

    def has_ship(i, j)
      self.battleships.each do |battleship|
        return true if battleship.is_at(i, j)
      end
      return false
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/battleship_games_controller.rb
class BattleshipGamesController < ApplicationController
  def index
    @games = BattleshipGame.all
  end

  def edit
  end

  def show
    @game = BattleshipGame.find(params[:id])
    @battleship = @game.battleships.new

  end

  def new
    @game = BattleshipGame.new
  end

  def create
    @game = BattleshipGame.new(params[:battleship_game].permit(:title))
    if @game.save
      redirect_to @game, notice: 'Battleship game successfully created.'
    else
      render :new
    end
  end
end

app/controllers/battleships_controller.rb
class BattleshipsController < ApplicationController
  def create
    @battleship = Battleship.new(params[:battleship].permit(:row, :column, :length, :battleship_game_id))
    if @battleship.save
      redirect_to @battleship.battleship_game, notice: 'Battleship game successfully created.'
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battleship_games_helper.rb
module BattleshipGamesHelper
end

app/views/battleship_games/edit.html.erb
<h1>BattleshipGames#edit</h1>
<p>Find me in app/views/battleship_games/edit.html.erb</p>

app/views/battleship_games/index.html.erb
<h1>Battleship Games</h1>

<p>
  <%= link_to( "+ Create new game", new_battleship_game_path) %>
</p>
<ul>
<% @games.each do |game| %>
  <li><%= link_to( game.updated_at.to_s + " – " + game.title, game) %></li>
<% end %>
</ul>

app/views/battleship_games/new.html.erb
<h1>Create new Battleship Game</h1>
<p>
  <%= link_to( "<< Back to index", battleship_games_path) %>
</p>
<%= form_for @game, url: {action: "create"} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit "Create" %>
<% end %>

app/views/battleship_games/show.html.erb
<h1><%= @game.updated_at.to_s + " – " + @game.title %></h1>

<p>
  <%= link_to( "<< Back to index", battleship_games_path) %>
</p>
<table>
  <tr>
    <td>

    </td>
    <% 10.times do |i| %>
    <td>
      <%= i %>
    </td>
    <% end %>
  </tr>
  <% 10.times do |i| %>
  <tr>
    <td>
      <%= i %>
    </td>
    <% 10.times do |j| %>
    <td>
      <%= @game.has_ship(i, j) ? "X" : "~" %>
    </td>
    <% end %>
  </tr>
  <% end %>
</table>

<h2>Create new battleship:</h2>
<%= form_for @battleship do |f| %>
  <%= f.hidden_field :battleship_game_id %>
  <%= f.label :row %>
  <%= f.text_field :row %>
  <%= f.label :column %>
  <%= f.text_field :column %>
  <%= f.label :length %>
  <%= f.text_field :length %>
  <%= f.submit "Create" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Battleships</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>